version: '2'

networks:
  net:

services:
  cli.jincor.com:
    container_name: cli.jincor.com
    image: hyperledger/fabric-tools:latest
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.jincor.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peers/peerOrganizations/org1.jincor.com/peer0.org1.jincor.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peers/peerOrganizations/org1.jincor.com/peer0.org1.jincor.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peerOrganizations/org1.jincor.com/peers/peer0.org1.jincor.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peerOrganizations/org1.jincor.com/users/Admin@org1.jincor.com/msp
    working_dir: /opt/gopath/src/
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/crypto-config/:/etc/hyperledger/crypto/
        - ../chaincode/github.com/JincorTech:/opt/gopath/src/github.com/JincorTech/
        - ../:/opt/sandbox
    depends_on:
      - orderer.jincor.com
      - peer0.org1.jincor.com
    networks:
      - net

  ca.org1.jincor.com:
    container_name: ca.org1.jincor.com
    extends:
      file: base-ca.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.org1.jincor.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=${FABRIC_CA_SERVER_CA_KEYFILE_ORG1}
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.org1.jincor.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=${FABRIC_CA_SERVER_TLS_KEYFILE_ORG1}
    ports:
      - "7054:7054"
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/org1.jincor.com/:/etc/hyperledger/fabric-ca-server-config

  ca.org2.jincor.com:
    container_name: ca.org2.jincor.com
    extends:
      file: base-ca.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.org2.jincor.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=${FABRIC_CA_SERVER_CA_KEYFILE_ORG2}
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.org2.jincor.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=${FABRIC_CA_SERVER_TLS_KEYFILE_ORG2}
    ports:
      - "8054:7054"
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/org2.jincor.com/:/etc/hyperledger/fabric-ca-server-config

  ca.org3.jincor.com:
    container_name: ca.org3.jincor.com
    extends:
      file: base-ca.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.org3.jincor.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=${FABRIC_CA_SERVER_CA_KEYFILE_ORG3}
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.org3.jincor.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=${FABRIC_CA_SERVER_TLS_KEYFILE_ORG3}
    ports:
      - "9054:7054"
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/org3.jincor.com/:/etc/hyperledger/fabric-ca-server-config

  orderer.jincor.com:
    container_name: orderer.jincor.com
    extends:
      file: base-orderer.yaml
      service: base-orderer
    environment:
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/base.block
      - ORDERER_GENERAL_LOCALMSPID=Orderer
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt,/etc/hyperledger/crypto/peer0Org1/tls/ca.crt,/etc/hyperledger/crypto/peer0Org2/tls/ca.crt,/etc/hyperledger/crypto/peer1Org1/tls/ca.crt,/etc/hyperledger/crypto/peer1Org2/tls/ca.crt]
    ports:
      - 7050:7050
    volumes:
        - ../artifacts/channels:/etc/hyperledger/configtx
        - ../artifacts/crypto-config/ordererOrganizations/jincor.com/orderers/orderer.jincor.com/:/etc/hyperledger/crypto/orderer
        - ../artifacts/crypto-config/peerOrganizations/org1.jincor.com/peers/peer0.org1.jincor.com/:/etc/hyperledger/crypto/peer0Org1
        - ../artifacts/crypto-config/peerOrganizations/org1.jincor.com/peers/peer1.org1.jincor.com/:/etc/hyperledger/crypto/peer1Org1
        - ../artifacts/crypto-config/peerOrganizations/org2.jincor.com/peers/peer0.org2.jincor.com/:/etc/hyperledger/crypto/peer0Org2
        - ../artifacts/crypto-config/peerOrganizations/org2.jincor.com/peers/peer1.org2.jincor.com/:/etc/hyperledger/crypto/peer1Org2
    networks:
      - net

  peer0.org1.jincor.com:
    container_name: peer0.org1.jincor.com
    extends:
      file: base-peer.yaml
      service: base-peer
    environment:
      - CORE_PEER_ID=peer0.org1.jincor.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.jincor.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.jincor.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.jincor.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/org1.jincor.com/peers/peer0.org1.jincor.com/:/etc/hyperledger/crypto/peer
        - ../chaincode/github.com/JincorTech:/opt/gopath/src/github.com/JincorTech/
    depends_on:
      - orderer.jincor.com

  peer1.org1.jincor.com:
    container_name: peer1.org1.jincor.com
    extends:
      file: base-peer.yaml
      service: base-peer
    environment:
      - CORE_PEER_ID=peer1.org1.jincor.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.jincor.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.jincor.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.jincor.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/org1.jincor.com/peers/peer1.org1.jincor.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.jincor.com

  peer0.org2.jincor.com:
    container_name: peer0.org2.jincor.com
    extends:
      file: base-peer.yaml
      service: base-peer
    environment:
      - CORE_PEER_ID=peer0.org2.jincor.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.jincor.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.jincor.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.jincor.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/org2.jincor.com/peers/peer0.org2.jincor.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.jincor.com

  peer1.org2.jincor.com:
    container_name: peer1.org2.jincor.com
    extends:
      file: base-peer.yaml
      service: base-peer
    environment:
      - CORE_PEER_ID=peer1.org2.jincor.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer1.org2.jincor.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.jincor.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.jincor.com:7051
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/org2.jincor.com/peers/peer1.org2.jincor.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.jincor.com

  peer0.org3.jincor.com:
    container_name: peer0.org3.jincor.com
    extends:
      file: base-peer.yaml
      service: base-peer
    environment:
      - CORE_PEER_ID=peer0.org3.jincor.com
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_ADDRESS=peer0.org3.jincor.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.jincor.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.jincor.com:7051
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/org3.jincor.com/peers/peer0.org3.jincor.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.jincor.com

  peer1.org3.jincor.com:
    container_name: peer1.org3.jincor.com
    extends:
      file: base-peer.yaml
      service: base-peer
    environment:
      - CORE_PEER_ID=peer1.org3.jincor.com
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_ADDRESS=peer1.org3.jincor.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.jincor.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.jincor.com:7051
    ports:
      - 9056:7051
      - 9058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/org3.jincor.com/peers/peer1.org3.jincor.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.jincor.com
